### ISSUE TITLE
Undocumented configuration for config.js

### ISSUE THREAD

**Issue by adioanca** [DT42/BerryNet#14]
I cannot find what info to put in config.js's:
// Authentication and channel information for LINE
config.LINETargetUserID = '';
config.LINEChannelSecret = '';
config.LINEChannelAccessToken = '';

Not having something here makes client.js to fail:
`Nov 23 14:21:01 raspberrypi systemd[1]: Started LINE client agent for notification.
Nov 23 14:21:04 raspberrypi node[16616]: /usr/local/berrynet/node_modules/@line/bot-sdk/dist/client.js:9
Nov 23 14:21:04 raspberrypi node[16616]:             throw new Error("no channel access token");
Nov 23 14:21:04 raspberrypi node[16616]:             ^
Nov 23 14:21:04 raspberrypi node[16616]: Error: no channel access token
Nov 23 14:21:04 raspberrypi node[16616]:     at new Client (/usr/local/berrynet/node_modules/@line/bot-sdk/dist/client.js:9:19)
Nov 23 14:21:04 raspberrypi node[16616]:     at Object.<anonymous> (/usr/local/berrynet/line.js:39:20)
Nov 23 14:21:04 raspberrypi node[16616]:     at Module._compile (module.js:570:32)
Nov 23 14:21:04 raspberrypi node[16616]:     at Object.Module._extensions..js (module.js:579:10)
Nov 23 14:21:04 raspberrypi node[16616]:     at Module.load (module.js:487:32)
Nov 23 14:21:04 raspberrypi node[16616]:     at tryModuleLoad (module.js:446:12)
Nov 23 14:21:04 raspberrypi node[16616]:     at Function.Module._load (module.js:438:3)
Nov 23 14:21:04 raspberrypi node[16616]:     at Module.runMain (module.js:604:10)
Nov 23 14:21:04 raspberrypi node[16616]:     at run (bootstrap_node.js:383:7)
Nov 23 14:21:04 raspberrypi node[16616]:     at startup (bootstrap_node.js:149:9)
Nov 23 14:21:04 raspberrypi systemd[1]: line.service: Main process exited, code=exited, status=1/FAILURE
Nov 23 14:21:04 raspberrypi systemd[1]: line.service: Unit entered failed state.
Nov 23 14:21:04 raspberrypi systemd[1]: line.service: Failed with result 'exit-code'.
`

Can you please explain what these settings should do?

BTW, I still don't see anything in IP:8080 web address.

**Comment by bafu** [comment]
@adioanca If LINE client is enabled, user can receive inference txt/img results in LINE app. LINE client is enabled by default, but the related configs are empty by default in config.js. If you are not using LINE client, you can ignore these errors directly, or disable LINE client in berrynet-manager.

In the next release, we will disable these additional clients by default, and provide more client tutorials. I will close this issue until this issue is really fixed.
