### ISSUE TITLE
[FR] Enable YOLOv4 engine

### ISSUE THREAD

**Issue by bafu** [DT42/BerryNet#48]
**Concept**
If we provide YOLOv4 engine, YOLO user can have a faster and more accurate detection engine to use.

**Suggested Implementation (if any)**

1. Study performance on TFLite (by [tensorflow-yolov4-tflite](https://github.com/hunglc007/tensorflow-yolov4-tflite)) and Darknet.
1. Implement v4 engine and service.

**Comment by bafu** [comment]
TFLite model: [yolov4-tiny-416.zip](https://github.com/DT42/BerryNet/files/4907988/yolov4-tiny-416.zip)

---
Steps to create the TFLite model

1. Convert raw model to TF checkpoints

    ```
    $ python3 save_model.py --weights ./data/yolov4-tiny.weights --output ./checkpoints/yolov4-tiny-416-tflite --input_size 416 --model yolov4 --tiny --framework tflite
    ```

1. Convert checkpoints to TFLite model

    ```
    $ python3 convert_tflite.py --weights ./checkpoints/yolov4-tiny-416-tflite --output ./checkpoints    /yolov4-tiny-416.tflite
    ```

1. Run a testing inference by using the TFLite model

    ```
    $ python3 detect.py --weights ./checkpoints/yolov4-tiny-416.tflite --size 416 --model yolov4 --image ./data/kite.jpg --framework tflite
    ```

**Comment by bafu** [comment]
Darknet benchmark

CPU: [Intel Pentium Gold G5400](https://ark.intel.com/content/www/us/en/ark/products/129951/intel-pentium-gold-g5400-processor-4m-cache-3-70-ghz.html)

* v4
  * Standard: 26s
  * Tiny: 2.1s
* v3
  * Standard: 28s
  * Tiny: 2.1s

**Comment by bafu** [comment]
Failed to run the TFLite model on RPi 4:

```
pi@raspberrypi:~/codes/tensorflow-yolov4-tflite $ python3 detect.py --weights ./checkpoints/yolov4-tiny-416.tflite --size 416 --model yolov4 --image ./data/kite.jpg --framework tflite
Traceback (most recent call last):
  File "detect.py", line 90, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "detect.py", line 49, in main
    interpreter = tf.lite.Interpreter(model_path=FLAGS.weights)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/interpreter.py", line 77, in __init__
    model_path))
ValueError: Didn't find op for builtin opcode 'RESIZE_BILINEAR' version '3'
Registration failed.
```

TF Wheel is from Pinto0309

```
pi@raspberrypi:~/codes/tensorflow-yolov4-tflite $ python3 -m pip freeze | grep tensorflow
tensorflow==1.14.0
tensorflow-estimator==1.14.0
```

**Comment by bafu** [comment]
YOLOv4 Tiny (TFLite) inference time on RPi 4

```
pi@raspberrypi:~/codes/tensorflow-yolov4-tflite $ python3 detect.py --weights ./checkpoints/yolov4-tiny-416.tflite --size 416 --model yolov4 --image ./data/kite.jpg --framework tflite                   
[{'name': 'input_1', 'index': 0, 'shape': array([  1, 416, 416,   3]), 'shape_signature': array([  1, 416, 416,   3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'Identity', 'index': 224, 'shape': array([   1, 2535,    4]), 'shape_signature': array([   1, 2535,    4]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'Identity_1', 'index': 206, 'shape': array([   1, 2535,   80]), 'shape_signature': array([   1, 2535,   80]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
Inference takes 0.8501577377319336 s
```

**Comment by bafu** [comment]
YOLOv4 Tiny TFLite model and label files: https://github.com/DT42/BerryNet/pull/49#issuecomment-674473590
